spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
enabled: false
servers:
  - host: 127.0.0.1:8080


---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
servers:
  - host: 127.0.0.1:8080
